export enum EStatus {
  NEW = 'NEW',
  INPROGRESS = 'INPROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
}


export enum ECustomFieldType {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  SELECT = 'SELECT',
  DATE = 'DATE',
  TIME = 'TIME',
  DATE_TIME = 'DATE_TIME',
  DATE_RANGE_PICKER = 'DATE_RANGE_PICKER',
  RANGE_PICKER = 'RANGE_PICKER',
  CHECKBOX = 'CHECKBOX',
  RADIO = 'RADIO',
  ATTACHMENT = 'ATTACHMENT',
  ADDRESS = 'ADDRESS',
  PHONE = 'PHONE',
  EMAIL = 'EMAIL',
  SWITCH = 'SWITCH',
  NOTE = 'NOTE',
}
